# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from .qtitle import ExecText

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 1000)
        self.MainWindow=MainWindow
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        # searchArea
        self.searchResultArea = QtWidgets.QTabWidget(self.centralwidget)
        self.searchResultArea.setGeometry(QtCore.QRect(270, 40, 561, 271))
        self.searchResultArea.setObjectName("tabWidget")

        # EditorArea
        self.IDFEditorDumpArea = QtWidgets.QScrollArea(self.centralwidget)
        self.IDFEditorDumpArea.setGeometry(QtCore.QRect(10, 40, 251, 271))
        self.IDFEditorDumpArea.setWidgetResizable(True)
        self.IDFEditorDumpArea.setObjectName("IDFEditorDumpArea")
        self.IDFEditorDumpArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.IDFEditorDumpArea.setWidgetResizable(False)

        # analysisArea
        self.analysisArea = QtWidgets.QGroupBox(self.centralwidget)
        self.analysisArea.setGeometry(QtCore.QRect(10, 340, 821, 271))
        self.analysisArea.setObjectName("EditorProcessingArea")

        # Execution Line Edit
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(10, 621, 821, 161))
        self.textBrowser.setObjectName("textBrowser")
        self.exectext = ExecText(self.centralwidget)
        self.exectext.setGeometry(QtCore.QRect(40, 790, 681, 31))
        self.exectext.setObjectName("exectext")
        self.exec = QtWidgets.QPushButton(self.centralwidget)
        self.exec.setGeometry(QtCore.QRect(730, 790, 101, 31))
        # self.exec.setMinimumHeight(30)
        self.exec.setObjectName("exec")
        self.exec_lable = QTitleButton(self.centralwidget)
        self.exec_lable.setGeometry(QtCore.QRect(10, 800, 31, 21))
        self.exec_lable.setObjectName("exec_lable")

        # Title
        self.SelectTheEditor = QTitle(self.centralwidget)
        self.SelectTheEditor.setGeometry(QtCore.QRect(40, 10, 261, 16))
        self.SelectTheEditor.setObjectName("SelectTheEditor")
        self.PutthemintoGroup = QTitleButton(self.centralwidget)
        self.PutthemintoGroup.setGeometry(QtCore.QRect(40, 320, 311, 60))
        self.PutthemintoGroup.setObjectName("PutthemintoGroup")
        self.ResultAnalysis = QTitleButton(self.centralwidget)
        self.ResultAnalysis.setGeometry(QtCore.QRect(40, 320, 311, 60))
        self.ResultAnalysis.setObjectName("ResultAnalysis")
        self.PutthemintoGroup.setStyleSheet(QTitleButton.selectStyleSheet)
        self.ResultAnalysis.setStyleSheet(QTitleButton.unselectStyleSheet)
        self.exportButton = QtWidgets.QPushButton(self.centralwidget)
        self.exportButton.setGeometry(QtCore.QRect(530, 590, 101, 31))
        self.exportButton.setMinimumWidth(150)
        self.exportButton.setObjectName("Params2CSV")

        # font
        font = QtGui.QFont()
        font.setPointSize(12)
        self.textBrowser.setFont(font)
        self.exectext.setFont(font)
        self.exectext.setAlignment(QtCore.Qt.AlignVCenter)

        font.setPointSize(15)
        self.SelectTheEditor.setFont(font)
        self.PutthemintoGroup.setFont(font)
        self.ResultAnalysis.setFont(font)
        self.exportButton.setFont(font)
        self.exec.setFont(font)
        self.exec_lable.setFont(font)

        MainWindow.setCentralWidget(self.centralwidget)

        # manu
        self.manubar = QtWidgets.QMenuBar(MainWindow)
        self.manubar.setGeometry(QtCore.QRect(0, 0, 800, 23))
        self.manubar.setObjectName("manubar")
        self.menuFiles = QtWidgets.QMenu(self.manubar)
        self.menuFiles.setObjectName("menuFiles")
        self.menuHelp = QtWidgets.QMenu(self.manubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuSimulation = QtWidgets.QMenu(self.manubar)
        self.menuSimulation.setObjectName("menuSimulation")
        MainWindow.setMenuBar(self.manubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionImport_Baseline_IDF = QtWidgets.QAction(MainWindow)
        self.actionImport_Baseline_IDF.setObjectName("actionImport_Baseline_IDF")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionSave_As = QtWidgets.QAction(MainWindow)
        self.actionSave_As.setObjectName("actionSave_As")
        self.actionLoad = QtWidgets.QAction(MainWindow)
        self.actionLoad.setObjectName("actionLoad")
        self.actionOpen_IDD_Folder = QtWidgets.QAction(MainWindow)
        self.actionOpen_IDD_Folder.setObjectName("actionOpen_IDD_Folder")
        self.actionOpen_Result_Folder = QtWidgets.QAction(MainWindow)
        self.actionOpen_Result_Folder.setObjectName("actionOpen_Result_Folder")
        self.actionOpen_Project_Folder = QtWidgets.QAction(MainWindow)
        self.actionOpen_Project_Folder.setObjectName("actionOpen_Project_Folder")
        self.actionReadMe = QtWidgets.QAction(MainWindow)
        self.actionReadMe.setObjectName("actionReadMe")
        self.actionIDFReference = QtWidgets.QAction(MainWindow)
        self.actionIDFReference.setObjectName("actionIDFReference")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionPythonDocument = QtWidgets.QAction(MainWindow)
        self.actionPythonDocument.setObjectName("actionPythonDocument")
        self.actionExport_Simulation_Params = QtWidgets.QAction(MainWindow)
        self.actionExport_Simulation_Params.setObjectName("actionExport_Simulation_Params")
        self.actionWrite = QtWidgets.QAction(MainWindow)
        self.actionWrite.setObjectName("actionWrite")
        self.actionSimulation = QtWidgets.QAction(MainWindow)
        self.actionSimulation.setObjectName("actionSimulation")
        self.actionContinueSimulation = QtWidgets.QAction(MainWindow)
        self.actionContinueSimulation.setObjectName("actionContinueSimulation")
        self.actionSet_Result_Folder = QtWidgets.QAction(MainWindow)
        self.actionSet_Result_Folder.setObjectName("actionSet_Result_Folder")
        self.actionExport_Select_Results = QtWidgets.QAction(MainWindow)
        self.actionExport_Select_Results.setObjectName("actionExport_Select_Results")
        self.menuFiles.addAction(self.actionImport_Baseline_IDF)
        self.menuFiles.addAction(self.actionSave)
        self.menuFiles.addAction(self.actionSave_As)
        self.menuFiles.addAction(self.actionLoad)
        self.menuFiles.addSeparator()
        self.menuFiles.addAction(self.actionOpen_IDD_Folder)
        self.menuFiles.addAction(self.actionOpen_Result_Folder)
        self.menuFiles.addAction(self.actionOpen_Project_Folder)
        self.menuHelp.addAction(self.actionPythonDocument)
        self.menuHelp.addAction(self.actionReadMe)
        self.menuHelp.addAction(self.actionIDFReference)
        self.menuHelp.addAction(self.actionAbout)
        self.menuSimulation.addAction(self.actionExport_Simulation_Params)
        self.menuSimulation.addAction(self.actionWrite)
        self.menuSimulation.addAction(self.actionSimulation)
        self.menuSimulation.addAction(self.actionContinueSimulation)
        self.menuSimulation.addSeparator()
        self.menuSimulation.addAction(self.actionSet_Result_Folder)
        self.menuSimulation.addAction(self.actionExport_Select_Results)
        self.manubar.addAction(self.menuFiles.menuAction())
        self.manubar.addAction(self.menuSimulation.menuAction())
        self.manubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.searchResultArea.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.arange()

    def arange(self,width=800,height=900):
        rowStretch=[5,30,5,40,20,5]
        columnStretch=[10,20,40,15]
        columnWidth = [int(stretch/sum(columnStretch)*width) for stretch in columnStretch]
        rowHeight = [int(stretch/sum(rowStretch)*height) for stretch in rowStretch]

        self.centruallayout = QtWidgets.QGridLayout(self.centralwidget)
        self.centruallayout.setContentsMargins(10, 10, 10, 10)
        self.centruallayout.setObjectName("CentrualLayout")
        # Policy:EditorTitle
        self.centruallayout.addWidget(self.SelectTheEditor, 0, 0, 1, 2)
        self.SelectTheEditor.setMinimumSize(columnWidth[0]+columnWidth[1], rowHeight[0])
        self.SelectTheEditor.setSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        self.SelectTheEditor.sizePolicy().setHorizontalStretch(1)
        self.centruallayout.addWidget(self.IDFEditorDumpArea, 1, 0, 1, 2)
        self.IDFEditorDumpArea.setSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        self.SelectTheEditor.sizePolicy().setHorizontalStretch(1)
        self.SelectTheEditor.sizePolicy().setVerticalStretch(1)
        self.centruallayout.addWidget(self.searchResultArea, 0, 2, 2, 2)
        self.searchResultArea.setSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        self.searchResultArea.sizePolicy().setHorizontalStretch(1)
        self.searchResultArea.sizePolicy().setVerticalStretch(1)

        # Policy:AnalysisAreaTitle
        self.centruallayout.addWidget(self.PutthemintoGroup, 2, 0, 1, 2)
        self.PutthemintoGroup.setMinimumSize(columnWidth[0]+columnWidth[1], rowHeight[2])
        self.PutthemintoGroup.setSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        self.PutthemintoGroup.sizePolicy().setHorizontalStretch(1)
        self.centruallayout.addWidget(self.ResultAnalysis, 2, 2, 1, 1)
        self.ResultAnalysis.setMinimumSize(columnWidth[2] , rowHeight[2])
        self.ResultAnalysis.setSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        self.ResultAnalysis.sizePolicy().setHorizontalStretch(1)
        self.centruallayout.addWidget(self.exportButton, 2, 3, 1, 1)
        self.exportButton.setFixedSize(columnWidth[3], rowHeight[2])
        self.exportButton.setSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)

        # Policy:AnalysisArea
        self.centruallayout.addWidget(self.analysisArea, 3, 0, 1, 4)
        self.analysisArea.setMinimumSize(width, rowHeight[3])
        self.analysisArea.setSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        self.analysisArea.sizePolicy().setHorizontalStretch(1)
        self.analysisArea.sizePolicy().setVerticalStretch(1)

        # Policy:TextBowser
        self.centruallayout.addWidget(self.textBrowser, 4, 0, 1, 4)
        self.textBrowser.setMinimumSize(width,rowHeight[4])
        self.textBrowser.setSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        self.textBrowser.sizePolicy().setHorizontalStretch(1)
        self.textBrowser.sizePolicy().setVerticalStretch(1)

        # Policy:Execution
        self.centruallayout.addWidget(self.exec_lable, 5, 0,1,1)
        self.exec_lable.setMinimumSize(columnWidth[0], rowHeight[5])
        self.exec_lable.setSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        self.centruallayout.addWidget(self.exectext, 5, 1, 1, 2)
        self.exectext.setMinimumSize(columnWidth[1]+columnWidth[2], rowHeight[5])
        self.exectext.setSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        self.centruallayout.addWidget(self.exec, 5, 3,1,1)
        self.exec.setMinimumSize(columnWidth[3], rowHeight[5])
        self.exec.setSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)



        for i in range(len(rowStretch)):
            self.centruallayout.setRowStretch(i, rowStretch[i])
            self.centruallayout.setRowMinimumHeight(i, int(rowStretch[i]/sum(rowStretch)*height))

        for i in range(len(columnStretch)):
            self.centruallayout.setRowStretch(i, columnStretch[i])
            self.centruallayout.setColumnMinimumWidth(i, int(columnStretch[i]/sum(columnStretch)*width))

        self.MainWindow.resize(width, height)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "EpeditorW 0.2.6"))

        self.exec.setText(_translate("MainWindow", "MoosasQA"))
        self.exec_lable.setText(_translate("MainWindow", "Clean"))
        self.SelectTheEditor.setText(_translate("MainWindow", "1. Select an Editor"))
        self.PutthemintoGroup.setText(_translate("MainWindow", "2. Put Editor in Group"))
        self.ResultAnalysis.setText(_translate("MainWindow", "3. Analysis the Result"))
        self.menuFiles.setTitle(_translate("MainWindow", "Files"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.menuSimulation.setTitle(_translate("MainWindow", "Simulation"))
        self.actionImport_Baseline_IDF.setText(_translate("MainWindow", "Import Baseline IDF..."))
        self.actionSave.setText(_translate("MainWindow", "Save..."))
        self.actionSave_As.setText(_translate("MainWindow", "Save As..."))
        self.actionLoad.setText(_translate("MainWindow", "Load..."))
        self.actionOpen_IDD_Folder.setText(_translate("MainWindow", "Open IDD Folder"))
        self.actionOpen_Result_Folder.setText(_translate("MainWindow", "Open Result Folder"))
        self.actionOpen_Project_Folder.setText(_translate("MainWindow", "Open Project Folder"))
        self.actionReadMe.setText(_translate("MainWindow", "ReadMe!"))
        self.actionIDFReference.setText(_translate("MainWindow", "IDFReference"))
        self.actionAbout.setText(_translate("MainWindow", "About..."))
        self.actionPythonDocument.setText(_translate("MainWindow", "PythonDocument"))
        self.actionExport_Simulation_Params.setText(_translate("MainWindow", "Export Simulation Params..."))
        self.actionWrite.setText(_translate("MainWindow", "Write *.idfs..."))
        self.actionSimulation.setText(_translate("MainWindow", "Simulation..."))
        self.actionContinueSimulation.setText(_translate("MainWindow", "Continue a Simulation..."))
        self.actionSet_Result_Folder.setText(_translate("MainWindow", "Set Result Folder..."))
        self.actionExport_Select_Results.setText(_translate("MainWindow", "Export Select Results..."))
from .qtitle import QTitle,QTitleButton
